development:
  adapter: postgresql
  encoding: unicode
  database: togo_stanza_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: togo_stanza_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: togo_stanza_production
  pool: 5
  username: postgres
  password: postgres
