development:
  adapter: postgresql
  encoding: unicode
  database: TogoStanza_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: TogoStanza_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: TogoStanza_production
  pool: 5
  username: postgres
  password:
